#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : comtypes
Version  : 1.1.10
Release  : 1
URL      : https://files.pythonhosted.org/packages/c4/37/c53b19c2c99208116ba813e3553a95b536cdde81c8183a87361537866f87/comtypes-1.1.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/c4/37/c53b19c2c99208116ba813e3553a95b536cdde81c8183a87361537866f87/comtypes-1.1.10.tar.gz
Summary  : Pure Python COM package
Group    : Development/Tools
License  : MIT
Requires: comtypes-bin = %{version}-%{release}
Requires: comtypes-python = %{version}-%{release}
Requires: comtypes-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
========
        
        **comtypes** is a lightweight Python COM package, based on the ctypes_
        FFI library, in less than 10000 lines of code (not counting the
        tests).
        
        **comtypes** allows to define, call, and implement custom and
        dispatch-based COM interfaces in pure Python.  It works on Windows and
        64-bit Windows. Windows CE support was dropped since comtypes==1.1.8.

%package bin
Summary: bin components for the comtypes package.
Group: Binaries

%description bin
bin components for the comtypes package.


%package python
Summary: python components for the comtypes package.
Group: Default
Requires: comtypes-python3 = %{version}-%{release}

%description python
python components for the comtypes package.


%package python3
Summary: python3 components for the comtypes package.
Group: Default
Requires: python3-core
Provides: pypi(comtypes)

%description python3
python3 components for the comtypes package.


%prep
%setup -q -n comtypes-1.1.10
cd %{_builddir}/comtypes-1.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637698893
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clear_comtypes_cache.py

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
